CREATE TABLE IF NOT EXISTS accounts(
   id serial PRIMARY KEY,
   confirmed INTEGER NOT NULL DEFAULT 0,
   confirmation_code INTEGER NOT NULL DEFAULT 0,
   created_at TIMESTAMP NOT NULL DEFAULT NOW(),
   updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users(
   id serial PRIMARY KEY,
   email VARCHAR(64) NOT NULL,
   "password" VARCHAR(512) NOT NULL,
   active INTEGER NOT NULL DEFAULT 0,
   created_at TIMESTAMP NOT NULL DEFAULT NOW(),
   updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
   account_id INTEGER NOT NULL REFERENCES accounts,
   account_owner INTEGER NOT NULL DEFAULT 0,
   confirmation_code INTEGER NOT NULL DEFAULT 0
);
